---
# Prerequisites installation recipe

- include_vars: fastqc_fix.yml
  when: node_type == 'front'

- name: 'Fix fastqc java fonts dependency: https://github.com/conda-forge/staged-recipes/issues/3164'
  command: '{{ conda_prefix }}/bin/conda install -y --name __fastqc@{{ fastqc_version }} openjdk --channel conda-forge'
  when: 
   - node_type == 'front'
   - GALAXY_VERSION in fastqc_fix_galaxy_versions
