---
# Galaxy dependencies installation recipe

#______________________________________
# fastqc

- include: fastqc_fix.yml
  when: type_of_node == 'front'

#______________________________________
# deeptools

- include: deeptools_fix.yml
  when: type_of_node == 'front'

#______________________________________
#htseq-count

- include: htseq-counts_fix.yml
  when: type_of_node == 'front'
  
#______________________________________
#fix-fasta-headers

- include: fix-fasta-headers_fix.yml
  when: type_of_node == 'front'
   
#______________________________________
#dr-disco

- include: dr-disco_fix.yml 
  when: type_of_node == 'front'
  
