---
# Galaxy dependencies installation recipe

#______________________________________
# fastqc

- include: fastqc_fix.yml
  when: type_of_node == 'front'

#______________________________________
# deeptools

- include: deeptools_fix.yml
  when: type_of_node == 'front'
