---
#______________________________________
# get Galaxy version from api

- name: Get galaxy version json :q
  get_url:
    url: '{{ galaxy_instance_url }}api/version'
    dest: '/tmp/galaxy_version.json'

- name: Set Galaxy version variable
  set_fact:
    GALAXY_VERSION: "{{ (lookup('file', '/tmp/galaxy_version.json') | from_json).get('version_major') }}"

- name: Print out Galaxy version
  shell: 'echo {{ GALAXY_VERSION }} >> /tmp/galaxy_version'

#______________________________________
# Get Conda version

- include: get_conda.yml
  when: slurm_node_type == 'front'
