---
# HTSEQ-COUNTS FIX
# ERROR:Fatal error: The HTSeq python package is not properly installed, contact Galaxy administrators
# /export/galaxy/database/job_working_directory/000/138/tool_script.sh: line 41: htseq-count: command not found
# /export/galaxy/database/job_working_directory/000/138/tool_script.sh: line 41: htseq-count: command not found


- name: 'Fix htseq_count htseq-count:command not found'
  command: '{{ conda_prefix }}/bin/conda install -y --name mulled-v1-9a164b56634e119cdc1c287da2a8663c2bb84f95bde65b82c675c42a4851a9cc htseq==0.6.1.post --channel bioconda'
  become_user: '{{ galaxy_user }}'
  become: true
  when:
   - htseq_count_conda_env.failed is not defined
   - GALAXY_VERSION in htseq_count_fix_galaxy_list
