---
# HTSEQ-COUNTS FIX
# ERROR:Fatal error: The HTSeq python package is not properly installed, contact Galaxy administrators
# /export/galaxy/database/job_working_directory/000/138/tool_script.sh: line 41: htseq-count: command not found
# add a fast check to speed up reconfiguration

- stat: path='{{conda_prefix}}/envs/mulled-v1-c9f488ec0e9a96bed61dcc2e074b26ce37ed596751861ff368fd824a2a5f11d4'
  register: htseq_env

- name: 'Fix htseq_count htseq-count:command not found'
  command: '{{ conda_prefix }}/bin/conda install -y --name mulled-v1-c9f488ec0e9a96bed61dcc2e074b26ce37ed596751861ff368fd824a2a5f11d4 htseq==0.9.1 --channel bioconda'
  become_user: '{{ galaxy_user }}'
  become: true
  when:
   - htseq_env.stat.exists
   - GALAXY_VERSION in htseq_count_fix_galaxy_list


