---
# tasks file for ansible-role-galaxycloud-tooldeps

# Get Galaxy and Conda versions
- include: get_version.yml

# Install tools dependencies
- include: prerequisites.yml 

# binaries (e.g. liftover)
- include: bin.yml
  when: install_bin|bool
