---
# tasks file for ansible-role-galaxycloud-tooldeps

- include: prerequisites.yml 
  when: check_galaxy|bool

# Check if Galaxy is up
- include: check_galaxy.yml
  when: check_galaxy|bool

# Get Galaxy and Conda versions
- include: get_version.yml

# Install tools dependencies
- include: dependencies.yml

# binaries (e.g. liftover)
- include: bin.yml
  when: install_bin|bool
