---
# LiftOver installation recipe

#---
# CentOS 7

- name: Install liftOver depedencencies
  yum: name=libpng12
       state=present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04
#FIXME
- name: Install liftOver depedencencies
  apt: name=libpng
       state=present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#---

- name: Create Liftover destination directory
  file: path=/opt/liftOver
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

- name: Download liftover
  get_url: url=http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/liftOver
           dest=/opt/liftOver/
           mode="a+x"

- name: Add /opt/liftOver to $PATH
  lineinfile: dest=/home/{{galaxy_user}}/.bashrc
              line="\n# Liftover binary path\nexport PATH=$PATH:/opt/liftOver"
              state=present

#---
# loc file configuration
