---
# Prerequisites installation recipe

#CentOS 7
- name: '[EL] Install common dependencies'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - dejavu-fonts-common # fix conda openjdk from defaults channels
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Ubuntu
- name: '[Ubuntu] Install common dependencies'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - fonts-dejavu-core # fix conda openjdk from defaults channels
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
