---
# Create directories for reference data and logs

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ galaxy_user }}"
    group: "{{ galaxy_user }}"
  with_items:
    - '{{ galaxy_log_path }}'

#______________________________________
# Copy script to read galaxy config file and conda envs parser
- name: Copy galaxy configuration file and conda parser scripts
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items:
    - { url: 'https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/master/galaxy/read_galaxy_config_file.py', dest: '/tmp/read_galaxy_config_file.py', mode: 'a+x' }
    - { url: 'https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/master/galaxy_tools/parse_conda_envs.py', dest: '/tmp/parse_conda_envs.py', mode: 'a+x' }

#______________________________________
# get galaxy version number to support for older galaxy versione (<18.01) when ini file was used

- name: Get Galaxy version number only for comparison
  set_fact:
    galaxy_version_number: "{{ GALAXY_VERSION | replace('release_','') }}"
  when: (GALAXY_VERSION != 'master') or (GALAXY_VERSION != 'dev')

- debug:
    msg: 'Galaxy version: {{ GALAXY_VERSION }}'

- debug:
    msg: 'Galaxy version number: {{ galaxy_version_number }}'
  when: galaxy_version_number is defined

#______________________________________
# Check galaxy.ini or galaxy.yml to enable support for older versions

- name: Check that the galaxy.yml.sample exists
  stat:
    path: '{{ galaxy_config_path }}/galaxy.yml.sample'
  register: stat_result

- name: 'Set galaxy.yml extension to yml for conditionals'
  set_fact:
    galaxy_config_file_extension: 'yml'
    galaxy_main_section: 'galaxy'
  when: stat_result.stat.exists|bool

- name: Set galaxy_config_file to galaxy.ini if galaxy.yml not exists
  set_fact:
    galaxy_config_file: '{{ galaxy_config_path }}/galaxy.ini'
    galaxy_config_file_extension: 'ini'
    galaxy_main_section: 'app:main'
  when: not stat_result.stat.exists|bool
