---
# RSEM installation recipe

#---
# CentOS 7

- name: Install RSEM depedencencies
  yum: name={{item}}
       state=present
  with_items:
    - perl-Switch
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04
# FIXME
- name: Install RSEM depedencencies
  apt: name={{item}}
       state=present
  with_items:
    - libpng
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#---

- name: Create RSEM destination directory
  file: path={{rsem_path}}
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  become_user: root
  become_method: sudo

- name: Download RSEM latest version
  get_url: url=https://github.com/deweylab/RSEM/archive/v{{rsem_version}}.tar.gz
           dest={{rsem_path}}/RSEM-{{rsem_version}}.tar.gz

# FIXME unarchive ansible module is not able to uncrompress files. A new module "uncompress" will be developed.
# The command module is used.
- name: Extract tar.gz file
  command: 'tar xvzf {{rsem_path}}/RSEM-{{rsem_version}}.tar.gz'
  args:
    chdir: '{{rsem_path}}'

- name: Running make
  command: 'make'
  args:
    chdir: '{{rsem_path}}/RSEM-{{rsem_version}}'

- name: Add RSEM path to to $PATH
  lineinfile: dest=/home/{{galaxy_user}}/.bashrc
              line="\n# RSEM binary path\nexport PATH=$PATH:/opt/rsem/RSEM-{{rsem_version}}"
              state=present
